function params = default_params
%DEFAULT_PARAMS Canonical struct for two-link swing benchmark (MATLAB reference vs MuJoCo).
% State order: x = [q1; q2; dq1; dq2] (rad, rad/s). Planar shoulder frame; gravity in -y if y up.
%
% Trunk fields are reserved for future whole-body extension (ignored by two_link_dynamics).

here = fileparts(mfilename('fullpath'));
params = struct();
params.model_version = 'Matlab_v2.1.0';
params.notes = '';
params.dt = 0.002;
params.t_end = 1.0;
params.q0 = [deg2rad(5); deg2rad(55)];
params.qd0 = [0; 0];

params.physics = struct( ...
    'l1', 0.30, 'l2', 0.35, ...
    'm1', 2.0, 'm2', 1.5, ...
    'lc1', 0.15, 'lc2', 0.20, ...
    'I1', 0.025, 'I2', 0.045, ...
    'g', 9.81, ...
    'damping_nm_s', [0; 0]);

params.control = struct( ...
    'type', 'sine', ...
    'tau_amp', 0.0, ...
    'tau_f_hz', 0.8, ...
    'tau_phase_deg', 30, ...
    'shoulder_onset', 0, ...
    'elbow_onset', 0, ...
    'shoulder_tau_amp', [], ...
    'elbow_tau_amp', [], ...
    'shoulder_tau', 0, ...
    'elbow_tau', 0, ...
    'piecewise_times', [], ...
    'piecewise_taus', []);

params.pronation = struct( ...
    'enable', false, ...
    'magnitude_rad', 0, ...
    'onset_s', 0.1, ...
    'rise_s', 0.05);

params.trunk = struct( ...
    'angle_rad', 0, ...
    'velocity_rad_s', 0, ...
    'torque_nm', 0, ...
    'onset_s', 0, ...
    'to_shoulder_delay_s', 0);

params.export = struct( ...
    'enable', false, ...
    'experiment_name', 'single_run', ...
    'run_id', '', ...
    'save_plots', false, ...
    'save_fig', false);

params.output_root = fullfile(here, 'outputs');
end
