function export_derived_outputs_csv(filepath, t, y)
%EXPORT_DERIVED_CSV Kinematics and energy channels for downstream tools.
T = table(t(:), y.p_ee(:, 1), y.p_ee(:, 2), y.v_ee(:, 1), y.v_ee(:, 2), ...
    y.speed(:), y.phi(:), y.energy_total(:), ...
    'VariableNames', {'time_s', 'ee_px_m', 'ee_py_m', 'ee_vx_m_s', 'ee_vy_m_s', ...
    'ee_speed_m_s', 'pronation_phi_rad', 'energy_total_j'});
writetable(T, filepath);
end
