function export_unity_swing_jsonl(filepath, frames)
%EXPORT_UNITY_SWING_JSONL Streaming-friendly: one JSON object per frame.
%
% Same payload as the CSV but as JSONL, so a Unity client (or a Python
% test harness) can consume it line-by-line. This is also the exact
% payload the UDP streamer pushes per packet.

[fid, msg] = fopen(filepath, 'w');
if fid < 0
    error('export_unity_swing_jsonl:open', 'Cannot open %s: %s', filepath, msg);
end
cleanup = onCleanup(@() fclose(fid));

N = numel(frames.t_s);
for k = 1:N
    payload = struct( ...
        'frame',         frames.frame(k), ...
        't_s',           frames.t_s(k), ...
        'phase_id',      frames.phase_id(k), ...
        'phase_label',   frames.phase_label{k}, ...
        'shoulder_pos',  frames.shoulder_pos(k, :), ...
        'shoulder_quat', frames.shoulder_quat(k, :), ...
        'elbow_pos',     frames.elbow_pos(k, :), ...
        'elbow_quat',    frames.elbow_quat(k, :), ...
        'wrist_pos',     frames.wrist_pos(k, :), ...
        'wrist_quat',    frames.wrist_quat(k, :), ...
        'racket_pos',    frames.racket_pos(k, :), ...
        'racket_quat',   frames.racket_quat(k, :), ...
        'racket_face_normal', frames.racket_face_normal(k, :), ...
        'racket_speed_mps',   frames.racket_speed_mps(k), ...
        'q_rad',         frames.q(k, :), ...
        'ball_pos',      frames.ball_pos(k, :), ...
        'ball_vel',      frames.ball_vel(k, :), ...
        'ball_spin',     frames.ball_spin(k, :), ...
        'contact_flag',  frames.contact_flag(k));
    fprintf(fid, '%s\n', jsonencode(payload));
end
end
