function out = unity_coords(op, varargin)
%UNITY_COORDS Convention helpers for the MATLAB (RHS Z-up) -> Unity hand-off.
%
% This project keeps RHS Z-up internally (aligns with MuJoCo, biomechanics
% norms, and existing PhD code). The Unity importer applies a documented
% conversion on its side. This file is the single source of truth for that
% conversion so any test, plot, or sanity check uses the same map.
%
% Conversion: RHS Z-up -> LHS Y-up
%   Position:  (x, y, z)        -> (x, z, y)
%   Quaternion: (w, qx, qy, qz) -> (-w, qx, qz, qy)   (handedness flip)
%   Direction (e.g. face normal): same as Position.
%
% Operations:
%   p_unity = unity_coords('pos_to_unity', p_world_zup)
%   q_unity = unity_coords('quat_to_unity', q_world_zup)
%   d_unity = unity_coords('dir_to_unity', d_world_zup)
%   schema  = unity_coords('csv_columns')      % cellstr column names
%   meta    = unity_coords('schema_meta')      % struct describing schema

if nargin < 1
    error('unity_coords:NotEnoughInputs', 'Operation name required.');
end

switch lower(op)
    case 'pos_to_unity'
        p = varargin{1}(:);
        out = [p(1); p(3); p(2)];
    case 'dir_to_unity'
        d = varargin{1}(:);
        out = [d(1); d(3); d(2)];
    case 'quat_to_unity'
        q = varargin{1}(:);
        out = [-q(1); q(2); q(4); q(3)];
    case 'csv_columns'
        out = local_csv_columns();
    case 'schema_meta'
        out = struct( ...
            'frame_convention',   'RHS_Z_up_internal_LHS_Y_up_for_unity', ...
            'angle_units',        'radians', ...
            'length_units',       'meters', ...
            'time_units',         'seconds', ...
            'quat_order',         'wxyz', ...
            'unity_axis_map',     'pos: (x,y,z)_zup -> (x,z,y)_yup; quat (w,x,y,z)_zup -> (-w,x,z,y)_yup', ...
            'columns',           {local_csv_columns()});
    otherwise
        error('unity_coords:UnknownOp', 'Unknown op: %s', op);
end
end

function cols = local_csv_columns()
% Master CSV schema. Per-frame, RHS Z-up. The Unity importer is responsible
% for axis flips per the schema_meta description.
cols = { ...
    'frame', ...
    't_s', ...
    'phase_id', ...
    'phase_label', ...
    'shoulder_pos_x', 'shoulder_pos_y', 'shoulder_pos_z', ...
    'shoulder_quat_w', 'shoulder_quat_x', 'shoulder_quat_y', 'shoulder_quat_z', ...
    'elbow_pos_x', 'elbow_pos_y', 'elbow_pos_z', ...
    'elbow_quat_w', 'elbow_quat_x', 'elbow_quat_y', 'elbow_quat_z', ...
    'wrist_pos_x', 'wrist_pos_y', 'wrist_pos_z', ...
    'wrist_quat_w', 'wrist_quat_x', 'wrist_quat_y', 'wrist_quat_z', ...
    'racket_pos_x', 'racket_pos_y', 'racket_pos_z', ...
    'racket_quat_w', 'racket_quat_x', 'racket_quat_y', 'racket_quat_z', ...
    'racket_face_normal_x', 'racket_face_normal_y', 'racket_face_normal_z', ...
    'racket_speed_mps', ...
    'q1_rad', 'q2_rad', 'q3_rad', 'q4_rad', 'q5_rad', ...
    'ball_pos_x', 'ball_pos_y', 'ball_pos_z', ...
    'ball_vel_x', 'ball_vel_y', 'ball_vel_z', ...
    'ball_spin_x', 'ball_spin_y', 'ball_spin_z', ...
    'contact_flag'};
end
