#!/usr/bin/env python3
"""Run native MATLAB parity benchmark even when matlab is not on PATH."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def find_matlab_binary(explicit: Path | None) -> Path:
    if explicit is not None:
        if explicit.exists():
            return explicit
        raise FileNotFoundError(f"MATLAB binary not found at --matlab-bin path: {explicit}")

    env_bin = os.environ.get("MATLAB_BIN", "").strip()
    if env_bin:
        env_path = Path(env_bin)
        if env_path.exists():
            return env_path

    for candidate in (
        Path("/Applications/MATLAB_R2025a.app/bin/matlab"),
        Path("/Applications/MATLAB_R2024b.app/bin/matlab"),
        Path("/Applications/MATLAB_R2024a.app/bin/matlab"),
        Path("/usr/local/bin/matlab"),
    ):
        if candidate.exists():
            return candidate

    which = subprocess.run(["which", "matlab"], capture_output=True, text=True)
    if which.returncode == 0 and which.stdout.strip():
        return Path(which.stdout.strip())

    raise FileNotFoundError(
        "Could not locate MATLAB binary. Set MATLAB_BIN or pass --matlab-bin."
    )


def newest_parity_dir(base_dir: Path) -> Path | None:
    dirs = [d for d in base_dir.glob("parity_*") if d.is_dir()]
    if not dirs:
        return None
    dirs.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return dirs[0]


def main() -> None:
    parser = argparse.ArgumentParser(description="Run native MATLAB parity benchmark and optional compare-signals.")
    parser.add_argument(
        "--matlab-bin",
        type=Path,
        default=None,
        help="Explicit path to MATLAB binary, e.g. /Applications/MATLAB_R2025a.app/bin/matlab",
    )
    parser.add_argument(
        "--benchmark-csv",
        type=Path,
        default=ROOT / "systematic_studies" / "outputs" / "swing_benchmark_timeseries.csv",
        help="Canonical benchmark CSV generated by swing_benchmark_mujoco_vs_bridge.py",
    )
    parser.add_argument(
        "--skip-compare",
        action="store_true",
        help="Only run MATLAB parity benchmark, skip compare_signals call.",
    )
    parser.add_argument(
        "--compare-script",
        type=Path,
        default=ROOT / "systematic_studies" / "compare_signals.py",
    )
    args = parser.parse_args()

    matlab_bin = find_matlab_binary(args.matlab_bin)
    matlab_v2_dir = ROOT / "Matlab_v2"
    out_root = matlab_v2_dir / "outputs" / "mujoco_benchmark"

    if not args.benchmark_csv.exists():
        raise FileNotFoundError(
            f"Benchmark CSV missing: {args.benchmark_csv}. "
            "Run systematic_studies/swing_benchmark_mujoco_vs_bridge.py first."
        )

    cmd_expr = (
        f"cd('{matlab_v2_dir.as_posix()}'); "
        f"benchmark_mujoco_parity('csv_path','{args.benchmark_csv.as_posix()}');"
    )
    cmd = [str(matlab_bin), "-batch", cmd_expr]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)

    latest = newest_parity_dir(out_root)
    if latest is None:
        raise FileNotFoundError(f"No parity output directory found under {out_root}")

    parity_csv = latest / "parity_timeseries.csv"
    if not parity_csv.exists():
        raise FileNotFoundError(
            f"Expected parity CSV missing after MATLAB run: {parity_csv}"
        )

    print(f"MATLAB parity output: {latest}")
    print(f"Canonical parity CSV: {parity_csv}")

    if args.skip_compare:
        return

    compare_cmd = [
        sys.executable,
        str(args.compare_script),
        "--parity-csv",
        str(parity_csv),
        "--out-figure",
        str(ROOT / "systematic_studies" / "outputs" / "figures" / "compare_signals_matlab_vs_mujoco.png"),
        "--out-json",
        str(ROOT / "systematic_studies" / "outputs" / "compare_signals_matlab_vs_mujoco_metrics.json"),
    ]
    print("Running:", " ".join(compare_cmd))
    compare_res = subprocess.run(compare_cmd, check=False)
    if compare_res.returncode == 2:
        print("compare_signals reported parity_ready=false (exit 2); MATLAB parity artifacts were still generated.")
        return
    if compare_res.returncode != 0:
        raise subprocess.CalledProcessError(compare_res.returncode, compare_cmd)


if __name__ == "__main__":
    main()
