function params = default_params_3d
%DEFAULT_PARAMS_3D Canonical struct for the 5-DOF 3D forward-swing demo.
%
% Phase 0 scope: kinematic playback (prescribed joint trajectories), 3D
% forward kinematics, ball flight + ball-racket impact, Unity-shaped
% export. No closed-loop dynamics yet (Phase 1).
%
% Coordinate frame (RHS, Z-up):
%   X: forward toward net (incoming ball travels in -X)
%   Y: lateral (positive to player's right by default)
%   Z: up (gravity in -Z)
%
% Joint set (5 DOF, right-handed forehand):
%   q1 - shoulder pitch   (about world Y)            -90  ..  +110 deg
%   q2 - shoulder yaw     (about world Z)            -110 ..  +60  deg
%   q3 - elbow flexion    (about local Y)              0  ..  +150 deg
%   q4 - forearm pronation(about forearm long axis) -90  ..  +90  deg
%   q5 - wrist flexion    (about local Y post pron)  -45  ..  +45  deg

here = fileparts(mfilename('fullpath'));
params = struct();
params.model_version = 'Matlab_v2.three_d.0.1.0';
params.dynamics_mode = 'kinematic_min_jerk';   % NB: not closed-loop dynamics
params.notes = 'Phase 0 kinematic forehand swing for Unity hand-off.';

% Time base
params.dt = 0.002;       % MATLAB sim step (s)
params.t_end = 1.5;      % total clip duration (s) - room for follow-through
params.unity_fps = 100;  % Unity fixed-update sample rate for the CSV export

% Anthropometry (m, kg, kg*m^2). Carried over from default_params + legacy
% three_link_tennis_model so future Phase-1 dynamics can reuse it.
params.physics = struct( ...
    'shoulder_pos_world', [0.0; 0.0; 1.40], ... % shoulder anchor in world
    'l_upperarm', 0.30, ...
    'l_forearm',  0.25, ...
    'l_racket',   0.32, ...   % shaft length from wrist to racket head centre
    'racket_head_radius', 0.16, ... % visual + impact area only
    'm1', 2.0, 'm2', 1.2, 'm3', 0.34, ...
    'lc1', 0.15, 'lc2', 0.12, 'lc3', 0.20, ...
    'I1', 0.025, 'I2', 0.015, 'I3', 0.015, ...
    'g', 9.81);

% Swing keyframes (DEGREES; converted to rad inside min_jerk_swing).
% Right-handed forehand: backswing rotates the racket back behind the
% player (negative q2), then forward swing accelerates it through contact.
params.swing = struct( ...
    'phase_t', [0.00 0.10 0.40 0.85 0.92 1.50], ...   % phase boundaries (s)
    'phase_labels', {{'ready', 'backswing', 'forward_swing', 'contact', 'follow_through'}}, ...
    'q_keyframes_deg', [ ...
       % ready  back   pre_imp  contact  follow_end
        -10,   -10,   -20,     30,      60; ...     % q1 shoulder pitch
          0,     0,   -90,     30,      60; ...     % q2 shoulder yaw
         90,    90,   110,     30,      90; ...     % q3 elbow flexion
          0,     0,   -60,     30,      60; ...     % q4 forearm pronation
          0,     0,   -20,      5,      30  ...     % q5 wrist flexion
    ], ...
    'contact_t', 0.85);    % when the racket is at the impact pose

% Ball setup (3D incoming ball; defaults match legacy/run_tennis_inverse_dyn).
params.ball = struct( ...
    'mass',   0.057, ...
    'radius', 0.0335, ...
    'Cd',     0.55, ...
    'Cl',     0.25, ...
    'rho',    1.225, ...
    'g',      9.81, ...
    'e',      0.75, ...        % coefficient of restitution
    'mu',     0.40, ...        % racket-string friction
    'p0',     [12.0;  0.0; 1.20], ...   % spawn position (m)
    'v0',     [-22.0; 0.5; 1.50], ...   % incoming velocity (m/s)
    'spin0',  [0; 0; -100]);            % topspin (rad/s about Z)

% Unity export schema knobs.
params.export = struct( ...
    'enable',           true, ...
    'experiment_name',  'three_d_forward_swing', ...
    'run_id',           '', ...                 % auto-fill via build_run_id
    'write_csv',        true, ...
    'write_jsonl',      true, ...
    'write_states_csv', true, ...
    'save_plots',       true, ...
    'rhs_zup',          true);                  % document the convention

% UDP streaming knobs (Phase 0 scaffold; off by default).
params.streaming = struct( ...
    'enable',     false, ...
    'host',       '127.0.0.1', ...
    'port',       55001, ...
    'fps',        100, ...
    'realtime',   true);

params.output_root = fullfile(fileparts(here), 'outputs');
end
